version: '3.7'

services:
  pg:
    image: postgres:11.2
    container_name: pg
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    ports:
      - 6543:5432
    restart: always
  go:
    build: .
    container_name: go-server
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - pg

volumes:
  data: